pipeline {
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }
    
    stages {
        stage('Prepare') {
            steps {                         
                git url: "https://github.com/CSID-DGU/2024-2-OSSPrac-openmind-08.git",
                    branch: 'main',
                    credentialsId: 'github'
            }
        }

        stage('Build') {
            steps {
                dir('teamsub6'){
                    sh 'docker compose build frontapp'
                }
            }
        }

        stage('Tag') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USR', passwordVariable: 'DOCKER_PSW')]) {
                    sh "docker tag teamsub6-frontapp $DOCKER_USR/teamsub6-frontapp:$BUILD_NUMBER"
                }
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USR', passwordVariable: 'DOCKER_PSW')]) {
                    sh "echo $DOCKER_PSW | docker login -u $DOCKER_USR --password-stdin"
                    sh "docker push $DOCKER_USR/teamsub6-frontapp:$BUILD_NUMBER"
                }
            }
        }
    }
}
