pipeline {
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }
    
    environment {
        DOCKER_CREDS = credentials('docker-hub')
    }
    
    stages {
        stage('Prepare') {
            steps {                         
                git url: "https://github.com/CSID-DGU/2024-2-OSSPrac-openmind-08.git",
                    branch: 'main',
                    credentialsId: 'github'
            }
        }

        stage('Build') {
            steps {
                dir('teamsub6'){
                    sh 'echo $DOCKER_CREDS_PSW  | docker login -u $DOCKER_CREDS_USR  --password-stdin'
                    sh 'docker compose build'
                }
            }
        }

        stage('Tag') {
            steps {
                sh 'docker tag teamsub6-frontapp $DOCKER_CREDS_USR/teamsub6-frontapp:$BUILD_NUMBER'
                sh 'docker tag teamsub6-backapp $DOCKER_CREDS_USR/teamsub6-backapp:$BUILD_NUMBER'
            }
        }

        stage('Push') {
            steps {
                sh 'echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR  --password-stdin'
                sh 'docker push $DOCKER_CREDS_USR/teamsub6-frontapp:$BUILD_NUMBER'
                sh 'docker push $DOCKER_CREDS_USR/teamsub6-backapp:$BUILD_NUMBER'
            }
        }
    }
}
